spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pessoa
    username: postgres
    password: Sen@c2023
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true